config/routes.rb
Rails.application.routes.draw do
  resources :comments

  resources :golf_events

  resources :users

  root 'welcome#index'
  get "/login" => "session#new"
  resource :session, only: [:create, :destroy]

    resources :users do
      resources :golf_events
    end

    resources :users do
      resources :comments
    end

    resources :golf_events do
      resources :comments
    end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :golf_event
end

app/models/golf_event.rb
class GolfEvent < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :golf_events
  has_many :comments, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionHelper
  helper_method :current_user, :logged_in?, :authenticate, :log_out!

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new

    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.create({:title => params[:comment][:title], :body => params[:comment][:body], :user_id => session[:user_id], :chapter_id => params[:chapter_id]})
    redirect_to(golf_event_path(params[:golf_event_id]))
  end


  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:title, :body, :user_id, :golf_event_id)
    end
end

app/controllers/golf_events_controller.rb
class GolfEventsController < ApplicationController
  before_action :set_saga, only: [:show, :edit, :update, :destroy]

  # GET /sagas
  # GET /sagas.json
  def index
    @golf_events = GolfEvent.all
  end

  # GET /sagas/1
  # GET /sagas/1.json
  def show
    @golf_event = GolfEvent.find(params[:id])
    @comments = GolfEvent.where("golf_event_id = ?", params[:id])
  end

  # GET /sagas/new
  def new
    @golf_event = GolfEvent.new
  end

  # GET /sagas/1/edit
  def edit
  end

  # POST /sagas
  # POST /sagas.json
  def create
    @golf_event = GolfEvent.create(title: params[:golf_event][:name], user_id: session[:user_id])
    redirect_to(user_path(session[:user_id]))
  end

  # PATCH/PUT /sagas/1
  # PATCH/PUT /sagas/1.json
  def update
    @golf_event.update(golf_event_params)
    redirect_to golf_event_path(params[:id])
  end

  # DELETE /sagas/1
  # DELETE /sagas/1.json
  def destroy
    @golf_event.destroy
    redirect_to user_path(session[:user_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_golf_event
      @golf_event = GolfEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def golf_event_params
      params.require(:golf_event).permit(:name, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      log_in(user)
      redirect_to(user_path(user))
    else
      flash[:error] = "Incorrect username or password."
      redirect_to(login_path)
    end
  end

  def destroy
    log_out!
    redirect_to(login_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate,            except: [:new, :create]
  before_action :load_user,               except: [:index, :new, :create]
  # before_action :authorize_admin_only,    only:   :index
  # before_action :authorize_user_only,     only:   :show
  before_action :authorize_user_or_admin, except: [:index, :show, :new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /users/1
  # GET /users/1.json
  def show
    user = User.find(params[:id])
    @golf_events = GolfEvent.where("user_id = ?", params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def password
  end

  # POST /users
  # POST /users.json
  def create
    # binding.pry
    @user = User.create(user_params)
    redirect_to user_path(@user)

    #  if @user.save
    #   log_in(@user)
    #   redirect_to user_path(@user)
    # else
    # render :new
    # end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
      @user.update(user_params)
      redirect_to(user_path(session[:user_id]))
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if current_user == @user
      @user.destroy
      log_out!
      flash[:notice] = "Chao tam biet!"
      redirect_to(root_path)
    else #admin is deleting....
      @user.destroy
      redirect_to(users_path)
    end
  end

  def confirm_delete
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(
        :name,
        :dob,
        :height,
        :gender,
        :city,
        :country,
        :image_url,
        :handicap,
        :interests,
        :password
        )
    end

    def user_password_params
      @user_password_params ||= params.require(:user).permit(
        :old_password,
        :password,
        :password_confirmation
        )
    end

    def load_user
      @user = User.find_by(id: params[:id])
      redirect_to root_path if !@user
    end

    # def authorize_admin_only
    #   unless current_user.is_admin?
    #     redirect_to user_path(current_user)
    #   end
    # end

    def authorize_user_only
      unless current_user == @user
        redirect_to user_path(current_user)
      end
    end

    def authorize_user_or_admin
      unless current_user == @user || current_user.is_admin?
        redirect_to user_path(current_user)
      end
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @golf_events = GolfEvent.all
    if session[:user_id]
      user = User.find_by(id: session[:user_id])
      redirect_to(user_path(user))
    # else
    #   redirect_to (login_path)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/golf_events_helper.rb
module GolfEventsHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def authenticate
    redirect_to login_path unless logged_in?
  end

  def log_out!
    session[:user_id] = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment, url: chapter_comments_path(params[:chapter_id])) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :add_comment %><br>
    <%= f.text_field :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<section class="main">
  <h1>Editing comment</h1>

  <%= form_for(@comment, url: chapter_comments_path(params[:chapter_id])) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :add_comment %><br>
    <%= f.text_field :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


  <%= link_to 'Show', @comment %> |
  <%= link_to 'Back', comments_path %>
</section>

app/views/comments/index.html.erb
<section class="main">
  <h1>Listing comments</h1>

  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th>User</th>
        <th>Chapter</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @comments.each do |comment| %>
        <tr>
          <td><%= comment.title %></td>
          <td><%= comment.body %></td>
          <td><%= comment.user %></td>
          <td><%= comment.chapter %></td>
          <td><%= link_to 'Show', comment %></td>
          <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
          <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Comment', new_comment_path %>
</section>

app/views/comments/new.html.erb
<section class="main">
  <h1>Add a Comment</h1>

  <%= form_for(@comment, url: chapter_comments_path(params[:chapter_id])) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :add_comment %><br>
    <%= f.text_field :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


</section>

app/views/comments/show.html.erb
<section class="main">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Title:</strong>
    <%= @comment.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= @comment.body %>
  </p>

  <p>
    <strong>User:</strong>
    <%= @comment.user %>
  </p>

  <p>
    <strong>Chapter:</strong>
    <%= @comment.chapter %>
  </p>

  <%= link_to 'Edit', edit_comment_path(@comment) %> |
  <%= link_to 'Back', comments_path %>
</section>

app/views/golf_events/_form.html.erb
<%= form_for(@golf_event) do |f| %>
  <% if @golf_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@golf_event.errors.count, "error") %> prohibited this golf_event from being saved:</h2>

      <ul>
      <% @golf_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/golf_events/_form.html1.erb
<%= form_for(@golf_event) do |f| %>
  <% if @golf_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@golf_event.errors.count, "error") %> prohibited this golf_event from being saved:</h2>

      <ul>
      <% @golf_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/golf_events/edit.html.erb
<section class="main">
  <h1>Editing Golf Event</h1>

  <%= form_for(@golf_event) do |f| %>
  <% if @golf_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@golf_event.errors.count, "error") %> prohibited this golf event from being saved:</h2>

      <ul>
      <% @golf_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


  <%= link_to 'Show', @golf_event %> |
  <%= link_to 'Back', golf_events_path %>
</section>

app/views/golf_events/index.html.erb
<section class="main">
  <h1>Listing Golf Events</h1>

  <table>
    <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Price</th>
      <th>Score</th>
      <th>Image url</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

    <tbody>
      <% @golf_events.each do |event| %>
        <tr>
          <td><%= golf_event.name %></td>
          <td><%= golf_event.user %></td>
          <td><%= link_to 'Show', golf_event %></td>
          <td><%= link_to 'Edit', edit_golf_event_path(golf_event) %></td>
          <td><%= link_to 'Destroy', golf_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Golf Event', new_golf_event_path %>
</section>

app/views/golf_events/new.html.erb
<section class="main">
  <h1>New Golf Event</h1>

<%= form_for(@golf_event) do |f| %>
  <% if @saga.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@saga.errors.count, "error") %> prohibited this saga from being saved:</h2>

      <ul>
      <% @saga.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

  <%= link_to 'Back', user_path(session[:user_id]) %>
</section>

app/views/golf_events/show.html.erb
<section class="main">
  <p id="notice"><%= notice %></p>


<p>
  <strong>Name:</strong>
  <%= @golf_event.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @golf_event.location %>
</p>

<p>
  <strong>Price:</strong>
  <%= @golf_event.price %>
</p>

<p>
  <strong>Score:</strong>
  <%= @golf_event.score %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @golf_event.image_url %>
</p>

<p>
  <strong>User:</strong>
  <%= @golf_event.user %>
</p>

  <p>
    <% @comments.each do |comment| %>
    <ul>
      <li>
        <tbody>
          <tr>
            <td>
              <%= link_to(comment.title, comment_path(comment.id)) %>
            </td>
          </tr>
        </tbody>
      </li>
    </ul>
    <% end %>
  </p>
  <% if @golf_event.user_id == session[:user_id] %>
  <%= link_to 'Add a Golf Event', new_golf_event_comment_path(@golf_event) %> |
  <%= link_to 'Edit', edit_golf_event_path(@golf_event) %> |
  <%= link_to 'Destroy', golf_event_path(@golf_event.id), method: :delete, data: { confirm: 'Are you sure?' } %> |

  <%= link_to 'back', user_path(session[:user_id]) %>

  <% else %>

  <%= link_to 'back', user_path(@golf_event.user_id) %>

  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>GolfBuddyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

  <%= csrf_meta_tags %>
</head>
<body>
   <nav>
      <% if session[:user_id] %>
        <%= link_to 'SAGA', user_path(session[:user_id]), class: 'logo' %>
      <% else %>
        <%= link_to 'SAGA', root_path, class: 'logo' %>
      <% end %>
    <ul class="nav">

      <% if session[:user_id] %>
        <%= link_to 'Logout', session_path, method: :delete %>
        <% else %>
      <li class="login"><%= link_to 'Log In', login_path %></li>
        <li class="signup"><%= link_to 'Sign Up', new_user_path %></li>
      <% end %>
    </ul>
  </nav>
  <div class="wrapper">

  <%= yield %>

  </div>

  <% if current_page?(controller: 'welcome', action: 'index')
 %>
    <footer class="relative">
        &copy;2014 Jennifer Nguyen
    </footer>
  <% else %>
    <footer>
        &copy;2014 Jennifer Nguyen
    </footer>
  <% end %>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.text_field :dob %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :handicap %><br>
    <%= f.number_field :handicap %>
  </div>
  <div class="field">
    <%= f.label :interests %><br>
    <%= f.text_field :interests %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<section class="main">
  <h1>Editing user</h1>

  <%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.text_field :dob %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :handicap %><br>
    <%= f.number_field :handicap %>
  </div>
  <div class="field">
    <%= f.label :interests %><br>
    <%= f.text_field :interests %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


  <%= link_to 'Show', @user %> |
  <%= link_to 'Back', users_path %>
</section>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dob</th>
      <th>Height</th>
      <th>Gender</th>
      <th>City</th>
      <th>Country</th>
      <th>Image url</th>
      <th>Handicap</th>
      <th>Interests</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.dob %></td>
        <td><%= user.height %></td>
        <td><%= user.gender %></td>
        <td><%= user.city %></td>
        <td><%= user.country %></td>
        <td><%= user.image_url %></td>
        <td><%= user.handicap %></td>
        <td><%= user.interests %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<section class="main">
  <h1>New user</h1>

  <%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.text_field :dob %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :handicap %><br>
    <%= f.text_field :handicap %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


  <%= link_to 'Back', users_path %>
</section>

app/views/users/show.html.erb
<h1 style="color: red"><%= notice %></h1>
<section class="main">
  <div class="left">

  <div class="profile_info">
    <p>
      <img src="<%= @user.image_url %>" width="100px">
    </p>
  </div>
  </div>
  <div class="right">
  <% if @user.id == session[:user_id] %>
  <p><%= link_to 'Edit Profile', edit_user_path(@user) %></p>
  <p><%= link_to 'Delete Profile', user_path(session[:user_id]), method: :delete, data: { confirm: 'Are you sure you want to delete your profile?' } %></p>
  <% end %>
  <br/>
   <p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @user.dob %>
</p>

<p>
  <strong>Height:</strong>
  <%= @user.height %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<p>
  <strong>City:</strong>
  <%= @user.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @user.country %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @user.image_url %>
</p>

<p>
  <strong>Handicap:</strong>
  <%= @user.handicap %>
</p>

<p>
  <strong>Interests:</strong>
  <%= @user.interests %>
</p>

  </div>

</section>
<section class="main">
    <h1>Sagas</h1>
    <% if @user.id == session[:user_id] %>
    <%= link_to "Create New Golf Event", new_golf_event_path, class: "saga_build" %> |
    <% end %>
    <% @golf_events.each do |event| %> </br>
    <%= link_to(golf_event.name, golf_event_path(golf_event.id)) %>
     <% @comments.each do |comment| %>
        <% if comment.golf_eventid == golf_event.id %>
        <ul>
        <li><img class="comment" src="<%= comment.image_url %>">&nbsp;&nbsp;<%= link_to(comment.title, comment_path(comment.id)) %></li>
        </ul>
        <% end %>

      <% end %>
    <% end %>
    <h1 style="color: red"><%= notice %></h1>
</section>

app/views/welcome/index.html.erb
<div id="splash">
  <% @golf_events.each do |event| %>
  <div class="left">
      <div class="overlay">
        <% if session[:user_id] = nil %>
          <a href="#"><%= golf_event.name %></a>
        <% else  %>
          <%= link_to(golf_event.name, golf_event_path(golf_event.id)) %>

        <% end %>

      </div>
      <img src="<%= golf_event.image_url %>">
  </div>
  <% end %>
</div>